FROM alpine:latest

RUN apk add --no-cache ca-certificates tzdata

COPY mmwf-cracked /app/server
COPY configs /app/configs
COPY rule_templates /app/rule_templates
COPY templates /app/templates

EXPOSE 8080
WORKDIR /app

ENTRYPOINT ["/app/server"]